[package]
name = "cubic-bezier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
vector2d = "2.2.0"
poloto = "18.0.6"
hypermelon = "0.5.5"